# Generated by Django 4.0.4 on 2022-05-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_group_posts_posts_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
