# Generated by Django 4.0.4 on 2022-05-16 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_group_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='posts.group'),
        ),
    ]
